### ISSUE TITLE
Moving workflow artifacts from legacy paths

### ISSUE THREAD

**Issue by awudome** [adobe/aem-cloud-migration#9]
### Expected Behaviour
Expecting workflow artifacts in legacy paths (like /etc/workflow/models/dam/update_asset) to be migrated to paths expected by AEM as a Cloud Service (/conf/global/settings/workflow)

### Actual Behaviour
When workflow artifacts in a legacy tree (/etc/workflow) are updated by the tool, they are updated in place and not migrated to /conf/global/settings/workflow

#### Platform and Version
Using version 0.2.4

#### Logs taken while reproducing problem

**Comment by ireasor** [comment]
Hello @awudome and thanks for the issue.  We weren't necessarily setting out to migrate workflows from /etc to /conf as a feature of this tool.  When you deploy the migrated workflow, does it work on the AEM as a Cloud Service environment?  I'm just trying to understand the impact of the issue.  Thanks!

**Comment by awudome** [comment]
Hi @ireasor - I have not tried deploying to the cloud so not sure if AEM will find the models in the legacy location. This was more of a question than a defect so I will go ahead and close this issue. Thank you.
